#!/usr/bin/perl

$indexfolder = "betageuze";    #   Das Verzeichnis, aus dem die Index-Tabelle erzeugt wird
$file = "/home/shared/bookmarks.xml";


use CGI qw/:standard/;           # load standard CGI routines
use XML::DOM;




# xml stuff

my $parser = new XML::DOM::Parser;
my $doc = $parser->parsefile ($file);

$level = 0;

$nodelist = $doc->getElementsByTagName( "folder" );

my $n = 0;
while ( $nodelist->item($n)->getElementsByTagName( "title", 0 )->item(0)->getFirstChild()->getData() ne $indexfolder ){
    $n++;
}
my $indexnode = $nodelist->item($n);
$nodelist = $indexnode->getElementsByTagName( "folder" );  # Hat jetzt alle folder von indexnode


# html



print header();                    # create the HTTP header
#    start_html('Betageuze bookmarks'); # start the HTML
#h1('hello world'),         # level 1 header


print '<table border=1 frame="border">';

$rows=5;
do {
    print "<tr>\n";
    for ( my $a=$rows-5; $a<$rows; $a++ ){
        my $node = $nodelist->item($a);
        if ( $node ){
            print "<td align=\"center\">".$node->getElementsByTagName( "title", 0 )->item(0)->getFirstChild()->getData()."</td>\n";
        }
    }
    print "</tr><tr valign=\"top\">\n";
    
    for ( my $a=$rows-5; $a<$rows; $a++ ){
        $node = $nodelist->item($a);
        if ( $node ){
            print "<td><ul>\n";
            my $bookmarklist = $node->getElementsByTagName( "bookmark", 0 );
            my $b = 0;
            $bookmark = $bookmarklist->item( $b );
            while ( $bookmark ){
                print "<li><a href=\"".
                    $bookmark->getAttributeNode("href")->getValue().
                    "\">";
                my $link= $bookmark->getElementsByTagName( "title", 0 )->item(0)->getFirstChild()->getData();
                $link =~ s/\//\/<wbr>/g;
                #$link =~ s/ / <wbr>/g;
                
                print $link.
                    "</a></li>\n";
                $b++;
                $bookmark = $bookmarklist->item( $b );
            }
            print "</ul></td>\n";
        }
    }
    
    print "</tr>\n";
    
    $rows+=5;
    
} while ( $node );


print "</table>\n";



#print end_html();                  # end the HTML


print "\n";
exit(0);

