#!/bin/sh
# run  command detached.
# find first free socket within ~/.dtach

let i=1;

while [ -e "$HOME/.dtach/$i" ] 
do 
		let i++
done

echo dtach socket: $HOME/.dtach/$i
dtach -n $HOME/.dtach/$i "$*"
echo "$*" > $HOME/.dtach/$i.nfo

