#!/bin/sh
#
# Lists the bookmarks located in the home bookmark file
#use Misc::Snippets;
#
#my @f = readfile( filename=>$ENV{HOME}.'/.shellbookmarks' );
#
#my $pos = 0;
#
#map { 
#		/^(.*?)=/; 
#		$pos = length($1) 
#			if (length($1)) > $pos; } 
#	@f;

#$pos -= 4;

#map { 
#		/^export (.*?)=(.*)$/;
#		print "$1";
#		print ' ' for ( 0..($pos-6-length($1)) );
#		print "$2\n";
#} @f;







perl -e 'print substr($_,7) while (<>)' ~/.shellbookmarks





