#!/bin/ash


BLACK=""$'\033[30m'""
GRAY=""$'\033[01;30m'""
LGREEN=""$'\033[01;32m'""
GREEN=""$'\033[32m'""
LRED=""$'\033[01;31m'""
RED=""$'\033[31m'""
YELLOW=""$'\033[01;33m'""
BROWN=""$'\033[33m'""
LBLUE=""$'\033[01;34m'""
BLUE=""$'\033[34m'""
PINK=""$'\033[01;35m'""
MAGENTA=""$'\033[00;35m'""
LMAGENTA=""$'\033[01;35m'""
CYAN=""$'\033[36m'""
LCYAN=""$'\033[01;36m'""
WHITE=""$'\033[01;37m'""
LGRAY=""$'\033[37m'""

BOLD=""$'\033[1m'""
FAINT=""$'\033[2m'""
CURSIVE=""$'\033[3m'""
UNDERLINE=""$'\033[4m'""
BLINK=""$'\033[5m'""
INVERTED=""$'\033[7m'""
NORM=""$'\033[0;0m'""



function fb(){
		echo '('`echo -n $1 | wc -c `') '\
$GREEN`echo $1 | tr -d "\n" | md5sum |  base91 | sed -E 's/^(.....).*/\1/'`$NORM  1>&2
}

function cmd(){
		echo -n "$1: " 1>&2
}


k=""
r=""
dpath=/dev/shm/.$USER-c

#echo -n 'passp: ' 1>&2
echo $GREEN`md5sum $0 | sum | sed 's/ *.$//' | tr -d "\n" | base64`$NORM $0 `whoami` "(Alt+h/^)" 1>&2
#| sed -E 's/^(......).*/\1/' 1>&2



if [ ! -e $dpath ]; then
		mkdir $dpath
		chmod go-rx $dpath
fi

if [ -e $dpath/c ]; then
    cmd "load"
		r=`cat $dpath/c`
		fb $r 
fi


e=0
x=''

c=$LCYAN
n=$NORM
function scripthelp(){
echo "
$c""ALT+Shift+[1-9]$n  Save   $c""F1-F9$n Load  $c""Alt+l$n list

$c""F10,Alt+r$n read c      $c""F11,Alt+c$n clear
$c""Alt+W$n     write c     $c""Alt+R/F12$n rm c

clipboard$n 
   $c""Alt+x$n write  $c""Alt+y$n  append from    
checksums$n 
   $c""Alt+1$n sha1    $c""Alt+2$n sha256   $c""Alt+3$n sha512   $c""Alt+5$n md5sum 
converter$n 
   $c""Alt+6$n base64  $c""Alt+b,Alt+9$n base91

$c""Alt+f$n Show checksum $c""Alt+D$n Show 
$c""Ret$n to stdout, exit 
" 1>&2

}


until [ $e = 1 ]
do
		echo -n "$x" 1>&2
		x='*'
		r="$r$k"
		k=`readkey -b`

		case "$k" in 
				"RET") # output to stdout, exit
						e=1
						echo 1>&2
						#echo $r 1>&2
						r=`echo -n $r | md5sum | sed "s/ *-$//" | tr -d "\n" | base91`
						echo -n $r
						exit 0
						;;
				"ALT+h" | "CTRL+H" | "^" )
						scripthelp
						k=""
						;;
				"ALT+c" | "F11")
						x="clear: "
						r=""
						k=""
						;;

				"ALT+m" | "ALT+5")
						k=""
						r=`echo -n $r | md5sum | sed "s/ *-$//"`
						x='$'
						;;
						#echo r: $r 1>&2
				"ALT+f")
						k=""
						echo 1>&2
						fb $r
						x=': '
						;;

				"ALT+9" | "ALT+b")
						k=""
						r=`echo -n $r | base91`
						x="+"
						#echo r: $r 1>&2
						;;
				"ALT+r" | "F10" )
						k=""
						r=`cat $dpath/c`
						x="load: "
						echo -n ":" 1>&2
						fb $r
						;;
				"ALT+5")
						x="copy "
						k=""
						r=`echo -n $r | md5sum | sed "s/ *-$//" | tr -d "\n" | base91`
						echo -n $r | xclip 
						;;
				"ALT+6")
						k=""
						r=`echo -n $r | base64`
						x="+"
						#echo r: $r 1>&2
						;;
				"ALT+1")
						k=""
						r=`echo -n $r | sha1sum | sed "s/ *-$//"`
						x='$'
						#echo r: $r 1>&2
						;;
				'ALT+2')
						k=""
						r=`echo -n $r | sha256sum | sed "s/ *-$//"`
						x='$'
						#echo r: $r 1>&2
						;;
				'ALT+3')
						k=""
						r=`echo -n $r | sha512sum | sed "s/ *-$//"`
						x='$'
						#echo r: $r 1>&2
						;;
				"ALT+R" | "F12")
						k=""
						x='RM c '
						rm $dpath/c
						;;
				"ALT+w")
						k=""
						x='WR c '
						echo -n $r > $dpath/c
						;;

				"ALT+D")
						k=""
						x=': '
						echo $r 1>&2
						;;
				"ALT+l")
						ls $dpath 1>&2
						;;

				*)
						if [ "XX" = `echo -n $k | sed 's/ALT+[!"§$%&/()]/XX/'` ]; then
								f=`echo -n $k | sed "s/ALT+/F/" | tr '!"§$%&/()=' '1234567890'`
								x=">$f: "
								echo -n $r > $dpath/c.$f
								f=""
								k=""
						fi
						if [ "XX" = `echo -n $k | sed "s/F./XX/"` ]; then
								x="<$k: "
								r=$r`cat $dpath/c.$k`
								#echo r load: $r 1>&2
								k=""
						fi
						;;
		esac

done

